server:
  port: 8082

spring:
  application:
    name: TICKETDAATA-TICKET-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://ahmedalfey:sani9999@hackathon.rflqj.mongodb.net/TicketDaata?retryWrites=true&w=majority
      database: ticketdaata_tickets
      auto-index-creation: true
      host: hackathon.rflqj.mongodb.net
      port: 27017
      username: ahmedalfey
      password: sani9999
      authentication-database: admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: false
  # Messaging Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 10000
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
        acknowledge-mode: auto
        prefetch: 10

# Messaging Mode Configuration
messaging:
  mode: rabbitmq # Options: inmemory, rabbitmq

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com.ticketdaata.ticketservice: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
    org.springframework.boot.autoconfigure.mongo: DEBUG
