server:
  port: 9003

spring:
  application:
    name: TICKETDAATA-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: TICKETDAATA-AUTH-SERVICE
          uri: lb://TICKETDAATA-AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: USER-SERVICE
          uri: lb://TICKETDAATA-USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: TICKET-SERVICE
          uri: lb://TICKETDAATA-TICKET-SERVICE
          predicates:
            - Path=/api/tickets/**
        - id: EVENT-SERVICE
          uri: lb://TICKETDAATA-EVENT-SERVICE
          predicates:
            - Path=/api/events/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
