server:
  port: ${AUTH_SERVICE_PORT:9000}

spring:
  application:
    name: TICKETDAATA-AUTH-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://ahmedalfey:sani9999@hackathon.rflqj.mongodb.net/TicketDaata?retryWrites=true&w=majority}
      database: ${MONGODB_DATABASE:ticketdaata_auth}
      auto-index-creation: true
      host: hackathon.rflqj.mongodb.net
      port: 27017
      username: ahmedalfey
      password: sani9999
      authentication-database: admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:TicketDaataSecretKeyForJWTTokenGenerationAndValidation2024}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost

logging:
  level:
    com.ticketdaata.authservice: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
    org.springframework.boot.autoconfigure.mongo: DEBUG
