server:
  port: 9002

spring:
  application:
    name: TICKETDAATA-ORDERS-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://ahmedalfey:sani9999@cluster0.iq0fhrp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ticketdaata_orders

# Order Configuration
orders:
  reservation:
    ttl-minutes: 15 # Time to live for temporary reservations
    cleanup-interval-minutes: 5 # How often to check for expired orders

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com.ticketdaata.ordersservice: DEBUG
